/* SK PLT Tools · formulargebundene VDE-0100-600-Dokumentenprüfung · 2.1.0.2-Beta */
(()=>{'use strict';
const ENGINE=window.SK_VDE_ENGINE,$=id=>document.getElementById(id);
const state={files:[],pages:[],data:{_confidence:{},_notRelevant:[],_visualPresence:{}},template:null,config:{},pending:[],history:[],confirmedFailIds:new Set(),current:0,mode:'',pdfjs:null,layoutScore:0};
const formatBytes=size=>size<1024?`${size} B`:size<1048576?`${(size/1024).toFixed(1)} KB`:`${(size/1048576).toFixed(1)} MB`;
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]));
const present=value=>value!==null&&value!==undefined&&String(value).trim()!=='';
function setStep(index){document.querySelectorAll('.steps span').forEach((el,i)=>el.classList.toggle('active',i===index));['uploadPanel','analysisPanel','reviewPanel','issuePanel','resultPanel'].forEach(id=>$(id).hidden=true);$(index===0?'uploadPanel':index===1?'analysisPanel':index===2?'reviewPanel':index===3?'issuePanel':'resultPanel').hidden=false;window.scrollTo({top:0,behavior:'smooth'})}
async function sha256(buffer){const bytes=await crypto.subtle.digest('SHA-256',buffer);return [...new Uint8Array(bytes)].map(value=>value.toString(16).padStart(2,'0')).join('')}
function renderFiles(){const host=$('fileList');host.replaceChildren();state.files.forEach((item,index)=>{const row=document.createElement('div');row.className='file-row';row.innerHTML=`<span class="type">${item.file.type==='application/pdf'?'PDF':'BILD'}</span><div><strong>${escapeHtml(item.file.name)}</strong><small>${formatBytes(item.file.size)} · ${escapeHtml(item.file.type||'Datei')}</small></div><button type="button" aria-label="${escapeHtml(item.file.name)} entfernen">×</button>`;row.querySelector('button').onclick=()=>{state.files.splice(index,1);renderFiles()};host.append(row)});$('clearFiles').disabled=!state.files.length;$('startAnalysis').disabled=!state.files.length}
function addFiles(files){for(const file of files){if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type))continue;if(state.files.length>=8)break;state.files.push({file})}renderFiles()}
async function loadTemplate(){const response=await fetch('../assets/vde0100-600-template.json?v=2.1.0.2-Beta',{cache:'no-store'});if(!response.ok)throw new Error(`Formularschema konnte nicht geladen werden (${response.status}).`);state.template=await response.json();state.config=state.template.config||{}}
async function pdfLibrary(){if(state.pdfjs)return state.pdfjs;const pdfjs=await import('../vendor/pdfjs/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('../vendor/pdfjs/pdf.worker.min.mjs',location.href).href;state.pdfjs=pdfjs;return pdfjs}
function canvasFor(width,height){const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(width));canvas.height=Math.max(1,Math.round(height));return canvas}
async function renderPdf(item,buffer){const pdfjs=await pdfLibrary(),pdf=await pdfjs.getDocument({data:new Uint8Array(buffer)}).promise,pages=[];let text='';for(let number=1;number<=pdf.numPages;number++){const page=await pdf.getPage(number),viewport=page.getViewport({scale:2.05}),canvas=canvasFor(viewport.width,viewport.height),context=canvas.getContext('2d',{alpha:false});await page.render({canvasContext:context,viewport}).promise;try{const content=await page.getTextContent();text+=' '+content.items.map(value=>value.str).join(' ')}catch{}pages.push({canvas,label:`${item.file.name} · Seite ${number}`,source:item.file.name,page:number})}return{pages,text}}
async function renderImage(item){const bitmap=await createImageBitmap(item.file),scale=Math.min(2400/Math.max(bitmap.width,bitmap.height),2),canvas=canvasFor(bitmap.width*scale,bitmap.height*scale),context=canvas.getContext('2d',{alpha:false});context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return{pages:[{canvas,label:item.file.name,source:item.file.name,page:1}],text:''}}
function rotateCanvas(source,degrees){if(!degrees)return source;const swap=degrees%180!==0,out=canvasFor(swap?source.height:source.width,swap?source.width:source.height),ctx=out.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,out.width,out.height);ctx.translate(out.width/2,out.height/2);ctx.rotate(degrees*Math.PI/180);ctx.drawImage(source,-source.width/2,-source.height/2);return out}
function lineDarkRatio(canvas,axis,position,start,end){const ctx=canvas.getContext('2d',{willReadFrequently:true}),w=canvas.width,h=canvas.height,band=axis==='y'?Math.max(2,Math.round(h*.0025)):Math.max(2,Math.round(w*.0025));let dark=0,total=0;if(axis==='y'){const y=Math.round(position*h),x0=Math.round(start*w),x1=Math.round(end*w),data=ctx.getImageData(x0,Math.max(0,y-band),Math.max(1,x1-x0),Math.min(h,y+band)-Math.max(0,y-band)).data;for(let i=0;i<data.length;i+=16){if((data[i]+data[i+1]+data[i+2])/3<185)dark++;total++}}else{const x=Math.round(position*w),y0=Math.round(start*h),y1=Math.round(end*h),data=ctx.getImageData(Math.max(0,x-band),y0,Math.min(w,x+band)-Math.max(0,x-band),Math.max(1,y1-y0)).data;for(let i=0;i<data.length;i+=16){if((data[i]+data[i+1]+data[i+2])/3<185)dark++;total++}}return total?dark/total:0}
function layoutScore(canvas){if(!state.template)return 0;const bounds=state.template.formBounds||[.08,.02,.89,.95],ys=state.template.layoutAnchorsY||[],xs=state.template.layoutAnchorsX||[];const horizontal=ys.map(y=>lineDarkRatio(canvas,'y',y,bounds[0],bounds[0]+bounds[2]));const vertical=xs.map(x=>lineDarkRatio(canvas,'x',x,bounds[1],bounds[1]+bounds[3]));const hScore=horizontal.filter(value=>value>.075).length/Math.max(1,horizontal.length),vScore=vertical.filter(value=>value>.18).length/Math.max(1,vertical.length),aspect=Math.min(canvas.width/canvas.height,canvas.height/canvas.width),aspectTarget=595/842,aspectScore=Math.max(0,1-Math.abs(aspect-aspectTarget)/.2);return Math.max(0,Math.min(1,hScore*.72+vScore*.18+aspectScore*.10))}
function orientPage(page){const candidates=page.canvas.width<=page.canvas.height?[{canvas:page.canvas,rotation:0},{canvas:rotateCanvas(page.canvas,180),rotation:180}]:[{canvas:rotateCanvas(page.canvas,90),rotation:90},{canvas:rotateCanvas(page.canvas,270),rotation:270}],ranked=candidates.map(item=>({...item,score:layoutScore(item.canvas)})).sort((a,b)=>b.score-a.score),best=ranked[0];return{...page,canvas:best.canvas,rotation:best.rotation,layoutScore:best.score}}
function regionPixels(canvas,rect,padding=0){const [nx,ny,nw,nh]=rect,x=Math.max(0,Math.round(nx*canvas.width)+padding),y=Math.max(0,Math.round(ny*canvas.height)+padding),w=Math.max(1,Math.round(nw*canvas.width)-padding*2),h=Math.max(1,Math.round(nh*canvas.height)-padding*2),ctx=canvas.getContext('2d',{willReadFrequently:true});return{x,y,w,h,data:ctx.getImageData(x,y,Math.min(w,canvas.width-x),Math.min(h,canvas.height-y)).data}}
function inkEvidence(canvas,rect,padding=2){const {data}=regionPixels(canvas,rect,padding);let dark=0,blue=0,total=0;for(let i=0;i<data.length;i+=16){const r=data[i],g=data[i+1],b=data[i+2],mean=(r+g+b)/3;if(mean<150)dark++;if(b-r>15&&b>g-12&&Math.max(r,g,b)-Math.min(r,g,b)>24)blue++;total++}return{darkRatio:total?dark/total:0,blueRatio:total?blue/total:0,marked:total?(dark/total>(state.config.checkboxInkThreshold||.055)||blue/total>.012):false}}
function parseMappedValue(key,text,parser){const def=ENGINE.FIELD_DEFS[key],clean=String(text||'').replace(/\s+/g,' ').trim();if(!clean)return null;if(parser==='number')return ENGINE.number(clean);if(parser==='date')return ENGINE.parseDate(clean)||null;if(parser==='list')return clean;if(parser==='text')return clean;if(parser==='signature')return clean?'present':null;if(def?.type==='choice'){const normalized=clean.toLowerCase();const option=def.options?.find(([,label])=>normalized.includes(String(label).toLowerCase())||String(label).toLowerCase().includes(normalized));return option?.[0]||null}return clean}
async function textBlocks(canvas){if(!('TextDetector' in window))return[];try{return await new window.TextDetector().detect(canvas)}catch{return[]}}
function blocksIn(blocks,rect,canvas){const [x,y,w,h]=rect;return blocks.filter(block=>{const b=block.boundingBox||{},cx=(Number(b.x)||0)+(Number(b.width)||0)/2,cy=(Number(b.y)||0)+(Number(b.height)||0)/2;return cx>=x*canvas.width&&cx<=(x+w)*canvas.width&&cy>=y*canvas.height&&cy<=(y+h)*canvas.height}).map(block=>block.rawValue||'').filter(Boolean).join(' ')}
function setDetected(key,value,confidence){if(!present(value)||!ENGINE.FIELD_DEFS[key])return;state.data[key]=value;state.data._confidence[key]=Math.max(Number(state.data._confidence[key]||0),confidence)}
function extractTemplateFields(canvas,blocks){const visual=state.data._visualPresence||(state.data._visualPresence={}),evidence={};for(const [key,map] of Object.entries(state.template.fieldMap||{})){
  if(map.checkboxes?.length){const marked=map.checkboxes.filter(option=>inkEvidence(canvas,option.box,2).marked);evidence[key]={marked:marked.map(item=>item.value)};if(map.parser==='multi'){if(marked.length)setDetected(key,marked.map(item=>item.value).join('; '),.9)}else if(marked.length===1)setDetected(key,marked[0].value,.92);else if(marked.length>1)visual[key]=true;continue}
  const ink=inkEvidence(canvas,map.region,3);evidence[key]=ink;if(ink.darkRatio>(state.config.fieldInkThreshold||.018)||ink.blueRatio>.004)visual[key]=true;const raw=blocksIn(blocks,map.region,canvas),value=parseMappedValue(key,raw,map.parser);if(present(value))setDetected(key,value,raw.length>2?.78:.7);if(map.parser==='signature'&&state.layoutScore>=Number(state.config.layoutScoreMin||.58)&&!present(value))setDetected(key,ink.marked?'present':'missing',ink.marked ? .82 : .76)
 }state.data._fieldEvidence=evidence}
function mergeData(target,source){for(const [key,value] of Object.entries(source||{})){if(key==='_confidence'){target._confidence={...(target._confidence||{}),...value};continue}if(!ENGINE.FIELD_DEFS[key])continue;if(present(value))target[key]=value}return target}
function extractionModeLabel(){return state.mode==='template-ocr'?'FORMULAR + OCR':state.mode==='template-visual'?'FORMULARLAYOUT ERKANNT':state.mode==='embedded-text'?'PDF-TEXT GELESEN':'MANUELLE FORMULARKLÄRUNG'}
function setProgress(percent,title,detail,stage){$('analysisPercent').textContent=`${percent} %`;$('analysisBar').style.width=`${percent}%`;$('analysisTitle').textContent=title;$('analysisDetail').textContent=detail;[...$('analysisLog').children].forEach((item,index)=>{item.classList.toggle('done',index<stage);item.classList.toggle('active',index===stage)})}
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function analyze(){if(!state.files.length)return;setStep(1);state.pages=[];state.data={_confidence:{},_notRelevant:[],_visualPresence:{}};state.history=[];state.confirmedFailIds.clear();try{
  setProgress(6,'Dateien werden eingelesen','Fingerabdruck und Dateityp werden ausschließlich lokal bestimmt.',0);await loadTemplate();let combinedText='';
  for(let index=0;index<state.files.length;index++){const item=state.files[index],buffer=await item.file.arrayBuffer();item.hash=await sha256(buffer);setProgress(12+Math.round((index/state.files.length)*20),'Seiten werden vorbereitet',`${item.file.name} wird lokal gerendert.`,1);const rendered=item.file.type==='application/pdf'?await renderPdf(item,buffer):await renderImage(item);state.pages.push(...rendered.pages);combinedText+=' '+rendered.text}
  setProgress(40,'Formularlayout wird erkannt',`${state.pages.length} Seite(n) werden am Linienraster der verbindlichen Mustervorlage ausgerichtet.`,1);state.pages=state.pages.map(orientPage);state.layoutScore=Math.max(0,...state.pages.map(page=>page.layoutScore));state.data._layoutScore=state.layoutScore;state.data._confidence.protocolType=Math.max(.55,state.layoutScore);state.data.protocolType=state.layoutScore>=Number(state.config.layoutScoreMin||.58)?'supported':'other';
  setProgress(58,'Formularfelder werden zugeordnet','Checkbox-Raster, Eingabezonen, Messwertfelder und Abschlussbereiche werden lokal ausgewertet.',2);const first=state.pages[0];let blocks=[];if(first){blocks=await textBlocks(first.canvas);extractTemplateFields(first.canvas,blocks)}if(combinedText.trim()){mergeData(state.data,ENGINE.parseText(combinedText));state.mode='embedded-text'}else state.mode=blocks.length?'template-ocr':state.layoutScore>=Number(state.config.layoutScoreMin||.58)?'template-visual':'manual';
  setProgress(80,'Vollständigkeit und Messwerte werden geprüft','Prüfpunkte 3.1–3.20, 4.1–4.4, 6.1/6.2 und 7.1–7.6 sowie Messwertbeziehungen werden kontrolliert.',3);await pause(180);refreshPending();setProgress(100,'Analyse abgeschlossen',`${state.pending.length} offene oder abweichende Punkte wurden ermittelt.`,4);await pause(260);renderReview();setStep(2)
 }catch(error){console.error(error);setProgress(100,'Analyse nicht abgeschlossen',error.message||String(error),4);$('analysisBar').style.background='#ff6673';setTimeout(()=>setStep(0),1800)}}
function displayValue(key,value){if(!present(value))return'Nicht sicher erkannt';const def=ENGINE.FIELD_DEFS[key];if(def?.options){const option=def.options.find(item=>item[0]===value);if(option)return option[1]}return `${value}${def?.unit?` ${def.unit}`:''}`}
function renderPreview(index=0){const frame=$('previewFrame'),tabs=$('previewTabs');frame.replaceChildren();tabs.replaceChildren();state.pages.forEach((page,pageIndex)=>{const button=document.createElement('button');button.type='button';button.textContent=String(pageIndex+1);button.classList.toggle('active',pageIndex===index);button.onclick=()=>renderPreview(pageIndex);tabs.append(button)});const source=state.pages[index]?.canvas;if(!source){frame.innerHTML='<p>Keine Vorschau verfügbar</p>';return}const preview=canvasFor(source.width,source.height),context=preview.getContext('2d');context.drawImage(source,0,0);frame.append(preview)}
function renderReview(){renderPreview();$('recognitionBadge').textContent=extractionModeLabel();$('layoutScore').textContent=`${Math.round(state.layoutScore*100)} %`;$('layoutScore').classList.toggle('low',state.layoutScore<Number(state.config.layoutScoreMin||.58));const rows=$('extractionTable');rows.replaceChildren();let count=0;for(const [key,def] of Object.entries(ENGINE.FIELD_DEFS)){if(!present(state.data[key]))continue;count++;const confidence=Number(state.data._confidence?.[key]??.7),row=document.createElement('div');row.className='data-row';row.innerHTML=`<span>${escapeHtml(def.label)}</span><strong>${escapeHtml(displayValue(key,state.data[key]))}</strong><b class="confidence ${confidence<.72?'low':''}">${Math.round(confidence*100)} %</b>`;rows.append(row)}$('statFields').textContent=String(count);$('statChecks').textContent=String(ENGINE.checkData(state.data,state.config).length);$('statOpen').textContent=String(state.pending.length);$('openIssues').textContent=state.pending.length?`Offene Punkte bearbeiten (${state.pending.length}) →`:'Ergebnis anzeigen →'}
function refreshPending(){const fresh=ENGINE.buildIssues(state.data,state.config);state.pending=fresh.filter(item=>!state.confirmedFailIds.has(item.id));if(state.current>=state.pending.length)state.current=Math.max(0,state.pending.length-1)}
function issueControl(issue){const def=issue.definition||{},host=$('correctionControl');host.replaceChildren();const label=document.createElement('label');label.append(document.createTextNode(`${def.label||'Korrektur'}${def.unit?` (${def.unit})`:''}`));let input;if(def.type==='choice'&&def.options){input=document.createElement('select');input.innerHTML='<option value="">Bitte auswählen</option>'+def.options.map(([value,text])=>`<option value="${escapeHtml(value)}">${escapeHtml(text)}</option>`).join('');if(present(issue.detected))input.value=String(issue.detected)}else if(def.type==='date'){input=document.createElement('input');input.type='date';if(present(issue.detected))input.value=String(issue.detected)}else if(def.type==='number'){input=document.createElement('input');input.type='number';input.inputMode='decimal';input.step='any';if(Number.isFinite(ENGINE.number(issue.detected)))input.value=String(ENGINE.number(issue.detected))}else if(issue.field==='insulationValues'||issue.field==='remarks'){input=document.createElement('textarea');input.rows=3;input.placeholder=issue.field==='insulationValues'?'z. B. >300; >300; >300':'Korrektur oder Maßnahme eintragen';if(present(issue.detected))input.value=String(issue.detected)}else{input=document.createElement('input');input.type='text';input.autocomplete='off';if(present(issue.detected))input.value=String(issue.detected)}input.id='issueInput';label.append(input);host.append(label);return input}
function renderIssueContext(issue){const host=$('issueSource');host.replaceChildren();const source=state.pages[0]?.canvas,map=state.template?.fieldMap?.[issue.field],rect=map?.context||map?.region;if(!source||!rect){host.hidden=true;return}host.hidden=false;const [nx,ny,nw,nh]=rect,padX=nw*.025,padY=nh*.2,x=Math.max(0,(nx-padX)*source.width),y=Math.max(0,(ny-padY)*source.height),w=Math.min(source.width-x,(nw+2*padX)*source.width),h=Math.min(source.height-y,(nh+2*padY)*source.height),scale=Math.min(2,900/w),out=canvasFor(w*scale,h*scale),ctx=out.getContext('2d');ctx.drawImage(source,x,y,w,h,0,0,out.width,out.height);ctx.strokeStyle='#ffb000';ctx.lineWidth=Math.max(3,4*scale);ctx.strokeRect((nx*source.width-x)*scale,(ny*source.height-y)*scale,nw*source.width*scale,nh*source.height*scale);host.append(out);const caption=document.createElement('small');caption.textContent='Markierter Ausschnitt aus dem hochgeladenen Protokoll';host.append(caption)}
function renderIssue(){if(!state.pending.length){renderResult();return}const issue=state.pending[state.current],total=state.history.length+state.pending.length,position=state.history.length+state.current+1;$('issueCounter').textContent=`${position} / ${total}`;$('issueProgress').style.width=`${Math.round((state.history.length/Math.max(1,total))*100)}%`;$('issueSection').textContent=issue.section.toUpperCase();$('issueTitle').textContent=issue.title;$('issueMessage').textContent=issue.message;$('detectedValue').textContent=displayValue(issue.field,issue.detected);renderIssueContext(issue);issueControl(issue);$('confirmFail').hidden=issue.status!=='fail';const queue=$('issueQueue');queue.replaceChildren();for(let i=0;i<Math.min(total,80);i++){const dot=document.createElement('span');dot.className=`issue-dot${i<state.history.length?' done':i===position-1?' current':''}`;queue.append(dot)}}
function resolveCurrent(kind){const issue=state.pending[state.current];if(!issue)return;const input=$('issueInput');if(kind==='corrected'){let value=input?.value?.trim();if(!value){input?.focus();return}if(issue.definition?.type==='number'){value=ENGINE.number(value);if(!Number.isFinite(value)){input.focus();return}}state.data[issue.field]=value;state.data._confidence[issue.field]=1;state.data._notRelevant=(state.data._notRelevant||[]).filter(key=>key!==issue.field);state.history.push({...issue,resolution:'korrigiert / bestätigt',resolvedValue:value})}else if(kind==='nrel'){if(!state.data._notRelevant.includes(issue.field))state.data._notRelevant.push(issue.field);state.history.push({...issue,resolution:'nicht relevant',resolvedValue:null})}else{state.confirmedFailIds.add(issue.id);state.history.push({...issue,resolution:'als n.i.O. bestätigt',resolvedValue:issue.detected})}refreshPending();state.current=0;renderIssue()}
function openIssues(){refreshPending();if(!state.pending.length){renderResult();return}setStep(3);renderIssue()}
function resultRow(check){const row=document.createElement('div');row.className=`result-row ${check.status==='fail'?'fail':''}`;row.innerHTML=`<b>${check.status==='fail'?'×':'✓'}</b><div><span>${escapeHtml(check.title)}</span><small>${escapeHtml(check.detail)}</small></div>`;return row}
function renderResult(){refreshPending();if(state.pending.length){setStep(3);renderIssue();return}const result=ENGINE.finalState(state.data,[],state.config),plausible=result.plausible;setStep(4);$('verdict').classList.toggle('fail',!plausible);$('verdictIcon').textContent=plausible?'✓':'×';$('verdictTitle').textContent=plausible?'Plausibel':'Nicht plausibel';$('verdictText').textContent=plausible?'Alle erkannten und anschließend geklärten Formularpunkte sind anhand der hinterlegten Regeln plausibel.':'Mindestens eine bestätigte Abweichung oder ein nicht plausibler Messwert bleibt bestehen.';const checks=$('resultChecks');checks.replaceChildren();result.checks.filter(item=>item.status==='pass'||item.status==='fail').forEach(item=>checks.append(resultRow(item)));if(!checks.children.length)checks.innerHTML='<p class="muted">Keine numerische Prüfregel war anwendbar.</p>';const log=$('resolutionLog');log.replaceChildren();state.history.forEach(item=>{const row=document.createElement('div');row.className=`result-row ${item.resolution.includes('n.i.O.')?'fail':''}`;row.innerHTML=`<b>${item.resolution.includes('n.i.O.')?'×':'✓'}</b><div><span>${escapeHtml(item.title)}</span><small>${escapeHtml(item.resolution)}${present(item.resolvedValue)?`: ${escapeHtml(displayValue(item.field,item.resolvedValue))}`:''}</small></div>`;log.append(row)});if(!state.history.length)log.innerHTML='<p class="muted">Keine manuelle Klärung erforderlich.</p>'}
function reset(){state.files=[];state.pages=[];state.data={_confidence:{},_notRelevant:[],_visualPresence:{}};state.pending=[];state.history=[];state.confirmedFailIds.clear();state.current=0;state.layoutScore=0;$('documentInput').value='';$('analysisBar').style.background='';renderFiles();setStep(0)}
function bindDrop(){const drop=$('dropZone');for(const name of ['dragenter','dragover'])drop.addEventListener(name,event=>{event.preventDefault();drop.classList.add('drag')});for(const name of ['dragleave','drop'])drop.addEventListener(name,event=>{event.preventDefault();drop.classList.remove('drag')});drop.addEventListener('drop',event=>addFiles([...event.dataTransfer.files]))}
function init(){if(!ENGINE)throw new Error('VDE-Prüfengine fehlt.');$('documentInput').addEventListener('change',event=>{addFiles([...event.target.files]);event.target.value=''});bindDrop();$('clearFiles').onclick=()=>{state.files=[];renderFiles()};$('startAnalysis').onclick=analyze;$('backUpload').onclick=()=>setStep(0);$('openIssues').onclick=openIssues;$('backReview').onclick=()=>{renderReview();setStep(2)};$('notRelevant').onclick=()=>resolveCurrent('nrel');$('confirmFail').onclick=()=>resolveCurrent('fail');$('applyCorrection').onclick=()=>resolveCurrent('corrected');$('printResult').onclick=()=>window.print();$('resetAll').onclick=reset;renderFiles()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();
