/* SK PLT Tools · robuste lokale VDE-0100-600-Dokumentenprüfung · 2.1.0.4-Beta */
(()=>{'use strict';
const ENGINE=window.SK_VDE_ENGINE,$=id=>document.getElementById(id);
const state={files:[],pages:[],data:{_confidence:{},_confidenceReason:{},_notRelevant:[],_visualPresence:{},_choiceMarks:{},_manualReviewed:[]},template:null,config:{},pending:[],history:[],confirmedFailIds:new Set(),current:0,mode:'',pdfjs:null,layoutScore:0,formStatus:'unknown',canMap:false,scoreBreakdown:{}};
const formatBytes=size=>size<1024?`${size} B`:size<1048576?`${(size/1024).toFixed(1)} KB`:`${(size/1048576).toFixed(1)} MB`;
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]));
const present=value=>value!==null&&value!==undefined&&String(value).trim()!=='';
const clamp=value=>Math.max(0,Math.min(1,Number(value)||0));
function setStep(index){const navStep=index<=1?index:index<=3?2:3;document.querySelectorAll('.steps span').forEach((el,i)=>el.classList.toggle('active',i===navStep));['uploadPanel','analysisPanel','reviewPanel','issuePanel','resultPanel'].forEach(id=>$(id).hidden=true);$(index===0?'uploadPanel':index===1?'analysisPanel':index===2?'reviewPanel':index===3?'issuePanel':'resultPanel').hidden=false;window.scrollTo({top:0,behavior:'smooth'})}
async function sha256(buffer){const bytes=await crypto.subtle.digest('SHA-256',buffer);return [...new Uint8Array(bytes)].map(value=>value.toString(16).padStart(2,'0')).join('')}
function renderFiles(){const host=$('fileList');host.replaceChildren();state.files.forEach((item,index)=>{const row=document.createElement('div');row.className='file-row';row.innerHTML=`<span class="type">${item.file.type==='application/pdf'?'PDF':'BILD'}</span><div><strong>${escapeHtml(item.file.name)}</strong><small>${formatBytes(item.file.size)} · ${escapeHtml(item.file.type||'Datei')}</small></div><button type="button" aria-label="${escapeHtml(item.file.name)} entfernen">×</button>`;row.querySelector('button').onclick=()=>{state.files.splice(index,1);renderFiles()};host.append(row)});$('clearFiles').disabled=!state.files.length;$('startAnalysis').disabled=!state.files.length}
function addFiles(files){for(const file of files){if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type))continue;if(state.files.length>=8)break;state.files.push({file})}renderFiles()}
async function loadTemplate(){const response=await fetch('../assets/vde0100-600-template.json?v=2.1.0.4-Beta',{cache:'no-store'});if(!response.ok)throw new Error(`Formularschema konnte nicht geladen werden (${response.status}).`);state.template=await response.json();state.config=state.template.config||{}}
async function pdfLibrary(){if(state.pdfjs)return state.pdfjs;const pdfjs=await import('../vendor/pdfjs/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('../vendor/pdfjs/pdf.worker.min.mjs',location.href).href;state.pdfjs=pdfjs;return pdfjs}
function canvasFor(width,height){const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(width));canvas.height=Math.max(1,Math.round(height));return canvas}
async function renderPdf(item,buffer){const pdfjs=await pdfLibrary(),pdf=await pdfjs.getDocument({data:new Uint8Array(buffer)}).promise,pages=[];let text='';for(let number=1;number<=pdf.numPages;number++){const page=await pdf.getPage(number),base=page.getViewport({scale:1}),scale=Math.min(2.55,2350/Math.max(base.width,base.height)),viewport=page.getViewport({scale}),canvas=canvasFor(viewport.width,viewport.height),context=canvas.getContext('2d',{alpha:false});context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);await page.render({canvasContext:context,viewport}).promise;try{const content=await page.getTextContent();text+=' '+content.items.map(value=>value.str).join(' ')}catch{}pages.push({canvas,label:`${item.file.name} · Seite ${number}`,source:item.file.name,page:number,fileHash:item.hash})}return{pages,text}}
async function renderImage(item){const bitmap=await createImageBitmap(item.file),scale=Math.min(2400/Math.max(bitmap.width,bitmap.height),2.6),canvas=canvasFor(bitmap.width*scale,bitmap.height*scale),context=canvas.getContext('2d',{alpha:false});context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return{pages:[{canvas,label:item.file.name,source:item.file.name,page:1,fileHash:item.hash}],text:''}}
function rotateCanvas(source,degrees){const normalized=((degrees%360)+360)%360;if(!normalized)return source;const rightAngle=normalized===90||normalized===270,angle=normalized*Math.PI/180,out=canvasFor(rightAngle?source.height:source.width,rightAngle?source.width:source.height),ctx=out.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,out.width,out.height);ctx.translate(out.width/2,out.height/2);ctx.rotate(angle);ctx.drawImage(source,-source.width/2,-source.height/2);return out}
function normalizeContrast(source){const out=canvasFor(source.width,source.height),ctx=out.getContext('2d',{alpha:false,willReadFrequently:true});ctx.drawImage(source,0,0);const image=ctx.getImageData(0,0,out.width,out.height),data=image.data,samples=[];const step=Math.max(4,Math.floor(Math.min(out.width,out.height)/300));for(let y=0;y<out.height;y+=step)for(let x=0;x<out.width;x+=step){const i=(y*out.width+x)*4;samples.push((data[i]*.299+data[i+1]*.587+data[i+2]*.114))}samples.sort((a,b)=>a-b);const low=samples[Math.floor(samples.length*.03)]??0,high=samples[Math.floor(samples.length*.97)]??255,span=Math.max(45,high-low);for(let i=0;i<data.length;i+=4){const value=clamp(((data[i]*.299+data[i+1]*.587+data[i+2]*.114)-low)/span)*255;data[i]=data[i+1]=data[i+2]=value;data[i+3]=255}ctx.putImageData(image,0,0);return out}
function structureDescriptor(canvas){const ctx=canvas.getContext('2d',{willReadFrequently:true}),image=ctx.getImageData(0,0,canvas.width,canvas.height),data=image.data,w=canvas.width,h=canvas.height,x0=Math.round(w*.02),x1=Math.round(w*.98),y0=Math.round(h*.01),y1=Math.round(h*.99),cols=18,rows=24,xBins=64,yBins=96,grid=new Float64Array(cols*rows),gridN=new Uint32Array(cols*rows),px=new Float64Array(xBins),pxN=new Uint32Array(xBins),py=new Float64Array(yBins),pyN=new Uint32Array(yBins),step=Math.max(1,Math.floor(Math.min(w,h)/600));for(let y=y0;y<y1;y+=step){const by=Math.min(yBins-1,Math.floor((y-y0)/(y1-y0)*yBins)),gy=Math.min(rows-1,Math.floor((y-y0)/(y1-y0)*rows));for(let x=x0;x<x1;x+=step){const bx=Math.min(xBins-1,Math.floor((x-x0)/(x1-x0)*xBins)),gx=Math.min(cols-1,Math.floor((x-x0)/(x1-x0)*cols)),i=(y*w+x)*4,dark=data[i]<185?1:0,g=gy*cols+gx;grid[g]+=dark;gridN[g]++;px[bx]+=dark;pxN[bx]++;py[by]+=dark;pyN[by]++}}return{grid:[...grid].map((v,i)=>v/Math.max(1,gridN[i])),x:[...px].map((v,i)=>v/Math.max(1,pxN[i])),y:[...py].map((v,i)=>v/Math.max(1,pyN[i]))}}
function cosine(a,b){if(!Array.isArray(a)||a.length!==b.length)return 0;let dot=0,aa=0,bb=0;for(let i=0;i<a.length;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i]}return aa&&bb?dot/Math.sqrt(aa*bb):0}
function lineDarkRatio(canvas,axis,position,start,end){const ctx=canvas.getContext('2d',{willReadFrequently:true}),w=canvas.width,h=canvas.height,band=axis==='y'?Math.max(2,Math.round(h*.0025)):Math.max(2,Math.round(w*.0025));let dark=0,total=0;if(axis==='y'){const y=Math.round(position*h),x0=Math.round(start*w),x1=Math.round(end*w),data=ctx.getImageData(x0,Math.max(0,y-band),Math.max(1,x1-x0),Math.min(h,y+band)-Math.max(0,y-band)).data;for(let i=0;i<data.length;i+=16){if(data[i]<185)dark++;total++}}else{const x=Math.round(position*w),y0=Math.round(start*h),y1=Math.round(end*h),data=ctx.getImageData(Math.max(0,x-band),y0,Math.min(w,x+band)-Math.max(0,x-band),Math.max(1,y1-y0)).data;for(let i=0;i<data.length;i+=16){if(data[i]<185)dark++;total++}}return total?dark/total:0}
function layoutScore(canvas){if(!state.template?.referenceDescriptor)return{total:0,structure:0,anchors:0,aspect:0};const descriptor=structureDescriptor(canvas),reference=state.template.referenceDescriptor,grid=cosine(descriptor.grid,reference.grid),y=cosine(descriptor.y,reference.y),x=cosine(descriptor.x,reference.x),structure=clamp(grid*.5+y*.35+x*.15),bounds=state.template.formBounds||[.08,.02,.89,.95],ys=state.template.layoutAnchorsY||[],xs=state.template.layoutAnchorsX||[],horizontal=ys.map(value=>lineDarkRatio(canvas,'y',value,bounds[0],bounds[0]+bounds[2])),vertical=xs.map(value=>lineDarkRatio(canvas,'x',value,bounds[1],bounds[1]+bounds[3])),anchors=clamp(horizontal.filter(value=>value>.075).length/Math.max(1,horizontal.length)*.8+vertical.filter(value=>value>.18).length/Math.max(1,vertical.length)*.2),aspect=Math.min(canvas.width/canvas.height,canvas.height/canvas.width),aspectTarget=595/842,aspectScore=clamp(1-Math.abs(aspect-aspectTarget)/.12),total=clamp(structure*.84+anchors*.11+aspectScore*.05);return{total,structure,anchors,aspect:aspectScore,grid,x,y}}
function orientAndNormalize(page){const orientations=[0,90,180,270].map(rotation=>{const canvas=rotateCanvas(page.canvas,rotation),analysis=normalizeContrast(canvas),score=layoutScore(analysis);return{canvas,analysis,rotation,deskew:0,score}}).sort((a,b)=>b.score.total-a.score.total);let best=orientations[0];for(const angle of [-2,-1,1,2]){const canvas=rotateCanvas(best.canvas,angle),analysis=normalizeContrast(canvas),score=layoutScore(analysis);if(score.total>best.score.total)best={canvas,analysis,rotation:best.rotation,deskew:angle,score}}return{...page,canvas:best.canvas,analysisCanvas:best.analysis,rotation:best.rotation,deskew:best.deskew,layoutScore:best.score.total,scoreBreakdown:best.score}}
function regionPixels(canvas,rect,inset=.04){const [nx,ny,nw,nh]=rect,padX=nw*inset,padY=nh*inset,x=Math.max(0,Math.round((nx+padX)*canvas.width)),y=Math.max(0,Math.round((ny+padY)*canvas.height)),w=Math.max(1,Math.round((nw-2*padX)*canvas.width)),h=Math.max(1,Math.round((nh-2*padY)*canvas.height)),ctx=canvas.getContext('2d',{willReadFrequently:true});return{x,y,w:Math.min(w,canvas.width-x),h:Math.min(h,canvas.height-y),data:ctx.getImageData(x,y,Math.min(w,canvas.width-x),Math.min(h,canvas.height-y)).data}}
function regionEvidence(canvas,rect,inset=.04){const {data,w,h}=regionPixels(canvas,rect,inset),stride=Math.max(1,Math.floor(Math.min(w,h)/36));let dark=0,blue=0,total=0,transitions=0,transitionTotal=0;for(let y=0;y<h;y+=stride){let previous=null;for(let x=0;x<w;x+=stride){const i=(y*w+x)*4,r=data[i],g=data[i+1],b=data[i+2],mean=r*.299+g*.587+b*.114,isDark=mean<150?1:0,isBlue=b-r>18&&b>g-14&&Math.max(r,g,b)-Math.min(r,g,b)>28;dark+=isDark;blue+=isBlue?1:0;total++;if(previous!==null){transitions+=previous!==isDark?1:0;transitionTotal++}previous=isDark}}return{darkRatio:dark/Math.max(1,total),blueRatio:blue/Math.max(1,total),transitions:transitions/Math.max(1,transitionTotal)}}
function baselineFor(key,value){const reference=state.template?.referenceEvidence||{};return value?reference.checkboxes?.[key]?.[value]||{}:reference.fields?.[key]||{}}
function evidenceDelta(evidence,baseline){return{dark:evidence.darkRatio-Number(baseline.darkRatio||0),blue:evidence.blueRatio-Number(baseline.blueRatio||0),transitions:evidence.transitions-Number(baseline.transitions||0)}}
function checkboxMarked(canvas,key,option){const evidence=regionEvidence(canvas,option.box,.24),delta=evidenceDelta(evidence,baselineFor(key,option.value)),score=clamp(Math.max(evidence.blueRatio*34,delta.blue*42,delta.dark*13+Math.max(0,delta.transitions)*2.5));return{...evidence,delta,score,marked:score>=Number(state.config.checkboxMarkScoreMin||.58)}}
function signatureState(canvas,key,rect,formConfidence){const evidence=regionEvidence(canvas,rect,.08),delta=evidenceDelta(evidence,baselineFor(key)),score=clamp(Math.max(evidence.blueRatio*30,delta.blue*38,delta.dark*18+Math.max(0,delta.transitions)*2.2)),presentSignature=score>=Number(state.config.signatureMarkScoreMin||.55),confidence=clamp((presentSignature ? .72 : .78)+formConfidence*.2+Math.min(.08,Math.abs(score-(state.config.signatureMarkScoreMin||.55))*.15));return{value:presentSignature?'present':'missing',confidence,evidence:{...evidence,delta,score}}}
function parseMappedValue(key,text,parser){const def=ENGINE.FIELD_DEFS[key],clean=String(text||'').replace(/\s+/g,' ').trim();if(!clean)return null;if(parser==='number')return ENGINE.number(clean);if(parser==='date')return ENGINE.parseDate(clean)||null;if(parser==='list'||parser==='text')return clean;if(def?.type==='choice'){const normalized=clean.toLowerCase(),option=def.options?.find(([,label])=>normalized.includes(String(label).toLowerCase())||String(label).toLowerCase().includes(normalized));return option?.[0]||null}return clean}
async function textBlocks(canvas){if(!('TextDetector' in window))return[];try{const detector=new window.TextDetector();return await detector.detect(canvas)}catch{return[]}}
function blocksIn(blocks,rect,canvas){const [x,y,w,h]=rect;return blocks.filter(block=>{const b=block.boundingBox||{},cx=(Number(b.x)||0)+(Number(b.width)||0)/2,cy=(Number(b.y)||0)+(Number(b.height)||0)/2;return cx>=x*canvas.width&&cx<=(x+w)*canvas.width&&cy>=y*canvas.height&&cy<=(y+h)*canvas.height}).map(block=>block.rawValue||'').filter(Boolean).join(' ')}
function setDetected(key,value,confidence,reason='Formularzone'){if(!present(value)||!ENGINE.FIELD_DEFS[key])return;const existing=Number(state.data._confidence[key]||0);if(confidence>=existing){state.data[key]=value;state.data._confidence[key]=clamp(confidence);state.data._confidenceReason[key]=reason}}
function extractTemplateFields(page,blocks){const canvas=page.canvas,formConfidence=page.layoutScore,visual=state.data._visualPresence||(state.data._visualPresence={}),choiceState=state.data._choiceMarks||(state.data._choiceMarks={}),evidenceLog={};for(const [key,map] of Object.entries(state.template.fieldMap||{})){if(key==='protocolType')continue;
  if(map.checkboxes?.length){const tested=map.checkboxes.map(option=>({option,result:checkboxMarked(canvas,key,option)})),marked=tested.filter(item=>item.result.marked),candidateMin=Number(state.config.checkboxCandidateScoreMin||.34),candidates=tested.filter(item=>item.result.score>=candidateMin).sort((a,b)=>b.result.score-a.result.score);choiceState[key]={confidentCount:marked.length,confidentValues:marked.map(item=>item.option.value),candidateCount:candidates.length,candidateValues:candidates.map(item=>item.option.value)};evidenceLog[key]={checkboxes:Object.fromEntries(tested.map(item=>[item.option.value,item.result]))};if(map.parser==='multi'){if(marked.length)setDetected(key,marked.map(item=>item.option.value).join('; '),clamp(.64+formConfidence*.25),'Checkbox-Ensemble')}else if(marked.length===1)setDetected(key,marked[0].option.value,clamp(.68+formConfidence*.27),'Checkbox-Ensemble');else if(marked.length===0&&candidates.length===1)setDetected(key,candidates[0].option.value,clamp(.48+formConfidence*.18),'unsicherer Checkbox-Kandidat');else if(marked.length>1)visual[key]=true;continue}
  const evidence=regionEvidence(canvas,map.region,.05),delta=evidenceDelta(evidence,baselineFor(key)),visuallyPresent=evidence.blueRatio>Number(state.config.fieldBlueDeltaMin||.002)||delta.dark>Number(state.config.fieldDarkDeltaMin||.006);evidenceLog[key]={...evidence,delta};if(visuallyPresent)visual[key]=true;const raw=blocksIn(blocks,map.region,canvas),value=parseMappedValue(key,raw,map.parser);if(present(value)){const textFactor=Math.min(.08,raw.length/120),confidence=clamp(.56+formConfidence*.30+textFactor);setDetected(key,value,confidence,'lokale Texterkennung + Feldzone')}
  if(map.parser==='signature'){const signature=signatureState(canvas,key,map.region,formConfidence);evidenceLog[key]=signature.evidence;setDetected(key,signature.value,signature.confidence,'referenzbereinigte Unterschriftszone')}
 }state.data._fieldEvidence=evidenceLog}
function mergeData(target,source){for(const [key,value] of Object.entries(source||{})){if(key==='_confidence'){for(const [field,confidence] of Object.entries(value)){if(Number(confidence)>=Number(target._confidence?.[field]||0))target._confidence[field]=confidence}continue}if(key==='_confidenceReason'){target._confidenceReason={...(target._confidenceReason||{}),...value};continue}if(!ENGINE.FIELD_DEFS[key])continue;if(present(value)&&Number(source._confidence?.[key]||0)>=Number(target._confidence?.[key]||0))target[key]=value}return target}
function extractionModeLabel(){if(state.formStatus==='uncertain')return'FORMULARIDENTITÄT UNSICHER';if(state.formStatus==='ambiguous')return'FORMULARIDENTITÄT ABWEICHEND';if(state.mode==='reference-hash')return'REFERENZFORMULAR';if(state.mode==='template-ocr')return'FORMULAR + LOKALE TEXTERKENNUNG';if(state.mode==='template-visual')return'FORMULARSTRUKTUR ERKANNT';if(state.mode==='embedded-text')return'FORMULAR + PDF-TEXT';return'MANUELLE FORMULARKLÄRUNG'}
function setProgress(percent,title,detail,stage){$('analysisPercent').textContent=`${percent} %`;$('analysisBar').style.width=`${percent}%`;$('analysisTitle').textContent=title;$('analysisDetail').textContent=detail;[...$('analysisLog').children].forEach((item,index)=>{item.classList.toggle('done',index<stage);item.classList.toggle('active',index===stage)})}
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function analyze(){if(!state.files.length)return;setStep(1);state.pages=[];state.data={_confidence:{},_confidenceReason:{},_notRelevant:[],_visualPresence:{},_choiceMarks:{},_manualReviewed:[]};state.history=[];state.confirmedFailIds.clear();try{
  setProgress(5,'Dateien werden eingelesen','Fingerabdruck und Dateityp werden ausschließlich lokal bestimmt.',0);await loadTemplate();let combinedText='';
  for(let index=0;index<state.files.length;index++){const item=state.files[index],buffer=await item.file.arrayBuffer();item.hash=await sha256(buffer);setProgress(10+Math.round((index/state.files.length)*22),'Seiten werden hochwertig gerendert',`${item.file.name} wird lokal normalisiert.`,1);const rendered=item.file.type==='application/pdf'?await renderPdf(item,buffer):await renderImage(item);state.pages.push(...rendered.pages);combinedText+=' '+rendered.text}
  setProgress(38,'Foto und Formular werden normalisiert',`${state.pages.length} Seite(n): Kontrast, 4 Orientierungen und Feinausrichtung werden verglichen.`,1);state.pages=state.pages.map(orientAndNormalize).sort((a,b)=>b.layoutScore-a.layoutScore);const first=state.pages[0];state.layoutScore=first?.layoutScore||0;state.scoreBreakdown=first?.scoreBreakdown||{};state.data._layoutScore=state.layoutScore;const exactReference=state.files.some(item=>item.hash===state.template.referenceForm.sha256),accept=Number(state.config.layoutScoreMin||.90),mappingMin=Number(state.config.layoutScoreMappingMin||.68);state.canMap=Boolean(exactReference||state.layoutScore>=mappingMin);state.formStatus=exactReference||state.layoutScore>=accept?'accepted':state.canMap?'ambiguous':'uncertain';state.data._formStatus=state.formStatus;state.data._fieldMappingAvailable=state.canMap;state.data.protocolType=state.formStatus==='accepted'?'supported':'other';state.data._confidence.protocolType=exactReference?1:clamp(state.layoutScore);state.data._confidenceReason.protocolType=exactReference?'SHA-256 der verbindlichen Referenz':'Struktur-Ensemble aus Raster, Projektionen und Linienankern';
  setProgress(60,'Formularfelder werden zugeordnet',state.canMap?'Referenzbereinigte Checkbox-, Handschrift- und Unterschriftszonen werden ausgewertet.':'Die Formularidentität ist stark abweichend; Pflichtfelder werden ohne automatische n.i.O.-Bewertung zur manuellen Zuordnung vorbereitet.',2);let blocks=[];if(first&&state.canMap){blocks=await textBlocks(first.analysisCanvas||first.canvas);extractTemplateFields(first,blocks)}if(combinedText.trim()){mergeData(state.data,ENGINE.parseText(combinedText));state.mode='embedded-text'}else if(exactReference)state.mode='reference-hash';else if(!state.canMap)state.mode='manual';else state.mode=blocks.length?'template-ocr':'template-visual';
  setProgress(82,'Vollständigkeit und Messwerte werden geprüft','Unsichere Werte, Pflichtfelder und sicherheitsrelevante Abweichungen erhalten getrennte Auflösungsregeln.',3);await pause(120);refreshPending();setProgress(100,'Analyse abgeschlossen',`${state.pending.length} offene oder abweichende Punkte wurden ermittelt.`,4);await pause(180);renderReview();setStep(2)
 }catch(error){console.error(error);setProgress(100,'Analyse nicht abgeschlossen',error.message||String(error),4);$('analysisBar').style.background='#ff6673';setTimeout(()=>setStep(0),1800)}}
function displayValue(key,value){if(!present(value))return'Nicht sicher erkannt';const def=ENGINE.FIELD_DEFS[key];if(def?.options){const option=def.options.find(item=>item[0]===value);if(option)return option[1]}return `${value}${def?.unit?` ${def.unit}`:''}`}
function renderPreview(index=0){const frame=$('previewFrame'),tabs=$('previewTabs');frame.replaceChildren();tabs.replaceChildren();state.pages.forEach((page,pageIndex)=>{const button=document.createElement('button');button.type='button';button.textContent=String(pageIndex+1);button.classList.toggle('active',pageIndex===index);button.onclick=()=>renderPreview(pageIndex);tabs.append(button)});const source=state.pages[index]?.canvas;if(!source){frame.innerHTML='<p>Keine Vorschau verfügbar</p>';return}const preview=canvasFor(source.width,source.height),context=preview.getContext('2d');context.drawImage(source,0,0);frame.append(preview)}
function renderReview(){renderPreview();$('recognitionBadge').textContent=extractionModeLabel();$('layoutScore').textContent=`${Math.round(state.layoutScore*100)} %`;$('layoutScore').classList.toggle('low',state.formStatus!=='accepted');const detail=$('recognitionDetail');if(detail)detail.textContent=state.formStatus==='accepted'?`Referenzabgleich bestanden · Struktur ${Math.round((state.scoreBreakdown.structure||0)*100)} % · Linien ${Math.round((state.scoreBreakdown.anchors||0)*100)} %`:`Technischer Hinweis: ${Math.round(state.layoutScore*100)} % Strukturpassung. Daraus entsteht kein n.i.O. und kein rotes Ergebnis. ${state.canMap?'Prüfbereiche werden zugeordnet; unsichere Kreuze und Werte werden einzeln geklärt.':'Die erforderlichen Angaben werden nacheinander manuell zugeordnet.'}`;const rows=$('extractionTable');rows.replaceChildren();let count=0;for(const [key,def] of Object.entries(ENGINE.FIELD_DEFS)){if(!present(state.data[key]))continue;count++;const confidence=Number(state.data._confidence?.[key]??.7),threshold=ENGINE.confidenceThreshold(def),row=document.createElement('div');row.className='data-row';row.title=state.data._confidenceReason?.[key]||'';row.innerHTML=`<span>${escapeHtml(def.label)}</span><strong>${escapeHtml(displayValue(key,state.data[key]))}</strong><b class="confidence ${confidence<threshold?'low':''}">${Math.round(confidence*100)} %</b>`;rows.append(row)}$('statFields').textContent=String(count);$('statChecks').textContent=String(ENGINE.checkData(state.data,state.config).length);$('statOpen').textContent=String(state.pending.length);$('openIssues').textContent=state.pending.length?`Offene Punkte bearbeiten (${state.pending.length}) →`:'Ergebnis anzeigen →'}
function refreshPending(){const fresh=ENGINE.buildIssues(state.data,state.config);state.pending=fresh.filter(item=>!state.confirmedFailIds.has(item.id));if(state.current>=state.pending.length)state.current=Math.max(0,state.pending.length-1)}
function buildInput(field,detected){const def=ENGINE.FIELD_DEFS[field]||{type:'text',label:field};let input;if(def.type==='choice'&&def.options){input=document.createElement('select');input.innerHTML='<option value="">Bitte auswählen</option>'+def.options.map(([value,text])=>`<option value="${escapeHtml(value)}">${escapeHtml(text)}</option>`).join('');if(present(detected))input.value=String(detected)}else if(def.type==='date'){input=document.createElement('input');input.type='date';if(present(detected))input.value=String(detected)}else if(def.type==='number'){input=document.createElement('input');input.type='number';input.inputMode='decimal';input.step='any';if(Number.isFinite(ENGINE.number(detected)))input.value=String(ENGINE.number(detected))}else if(field==='insulationValues'||field==='remarks'){input=document.createElement('textarea');input.rows=3;input.placeholder=field==='insulationValues'?'z. B. >300; >300; >300':'Korrektur oder Maßnahme eintragen';if(present(detected))input.value=String(detected)}else{input=document.createElement('input');input.type='text';input.autocomplete='off';if(present(detected))input.value=String(detected)}input.dataset.field=field;return input}
function issueControl(issue){const host=$('correctionControl');host.replaceChildren();if(issue.groupControl==='location'){const intro=document.createElement('p');intro.className='field-group-hint';intro.textContent='Mindestens zwei Ortsfelder ausfüllen oder bestätigen.';host.append(intro);const grid=document.createElement('div');grid.className='field-group-grid';for(const field of issue.fields){const def=ENGINE.FIELD_DEFS[field],label=document.createElement('label');label.append(document.createTextNode(def.label));label.append(buildInput(field,state.data[field]));grid.append(label)}host.append(grid);return null}const label=document.createElement('label'),def=issue.definition||{};label.append(document.createTextNode(`${def.label||'Korrektur'}${def.unit?` (${def.unit})`:''}`));const input=buildInput(issue.field,issue.detected);input.id='issueInput';label.append(input);host.append(label);return input}
function renderIssueContext(issue){const host=$('issueSource');host.replaceChildren();const source=state.pages[0]?.canvas,map=state.template?.fieldMap?.[issue.field],rect=map?.context||map?.region;if(!source||!rect){host.hidden=true;return}host.hidden=false;const [nx,ny,nw,nh]=rect,padX=nw*.025,padY=nh*.2,x=Math.max(0,(nx-padX)*source.width),y=Math.max(0,(ny-padY)*source.height),w=Math.min(source.width-x,(nw+2*padX)*source.width),h=Math.min(source.height-y,(nh+2*padY)*source.height),scale=Math.min(2,900/w),out=canvasFor(w*scale,h*scale),ctx=out.getContext('2d');ctx.drawImage(source,x,y,w,h,0,0,out.width,out.height);ctx.strokeStyle='#ffb000';ctx.lineWidth=Math.max(3,4*scale);ctx.strokeRect((nx*source.width-x)*scale,(ny*source.height-y)*scale,nw*source.width*scale,nh*source.height*scale);host.append(out);const caption=document.createElement('small');caption.textContent='Markierter Ausschnitt aus dem hochgeladenen Protokoll';host.append(caption)}
function renderIssue(){if(!state.pending.length){renderResult();return}const issue=state.pending[state.current],total=state.history.length+state.pending.length,position=state.history.length+state.current+1,formIdentity=issue.groupControl==='formIdentity';$('issueCounter').textContent=`${position} / ${total}`;$('issueProgress').style.width=`${Math.round((state.history.length/Math.max(1,total))*100)}%`;$('issueSection').textContent=issue.section.toUpperCase();$('issueTitle').textContent=issue.title;$('issueMessage').textContent=issue.message;$('detectedValue').textContent=formIdentity?`${Math.round(state.layoutScore*100)} % Strukturpassung · technischer Hinweis`:issue.groupControl==='location'?`${issue.fields.filter(field=>present(state.data[field])).length} von mindestens 2 Ortsfeldern bestätigt`:displayValue(issue.field,issue.detected);renderIssueContext(issue);if(formIdentity)$('correctionControl').replaceChildren();else issueControl(issue);$('formIdentityActions').hidden=!formIdentity;$('normalIssueActions').hidden=formIdentity;if(!formIdentity){$('confirmFail').hidden=!(issue.status==='fail'||issue.missingRequired);$('confirmFail').textContent=issue.status==='fail'?'Abweichung als Mangel bestätigen':issue.kind==='missing-choice'?'Fehlendes Kreuz als Mangel bestätigen':'Fehlende Pflichtangabe als Mangel bestätigen';$('notRelevant').hidden=!issue.allowNotRelevant;$('notRelevant').disabled=!issue.allowNotRelevant;$('notRelevant').textContent=issue.notRelevantMode==='value'?'Fachlich nicht relevant':'Optionales Feld nicht relevant';$('applyCorrection').hidden=false}const policy=$('resolutionPolicy');if(policy)policy.textContent=formIdentity?'Die Formularidentität ist kein fachliches Prüfergebnis. Wählen Sie, ob die erkannten Zuordnungen verwendet, vollständig manuell geprüft oder durch eine andere Datei ersetzt werden sollen.':issue.allowNotRelevant?'„Nicht relevant“ ist für diesen fachlich optionalen Punkt zulässig.':'Pflichtangaben und sicherheitsrelevante Abweichungen können nicht als „nicht relevant“ übersprungen werden.';const queue=$('issueQueue');queue.replaceChildren();for(let i=0;i<Math.min(total,80);i++){const dot=document.createElement('span');dot.className=`issue-dot${i<state.history.length?' done':i===position-1?' current':''}`;queue.append(dot)}}
function showControlError(message){let error=$('correctionControl').querySelector('.field-error');if(!error){error=document.createElement('p');error.className='field-error';$('correctionControl').prepend(error)}error.textContent=message}
function resolveCurrent(kind){const issue=state.pending[state.current];if(!issue)return;if(kind==='nrel'&&!issue.allowNotRelevant)return;
  if(kind==='corrected'&&issue.groupControl==='location'){for(const input of $('correctionControl').querySelectorAll('[data-field]')){const value=input.value.trim();if(value){state.data[input.dataset.field]=value;state.data._confidence[input.dataset.field]=1;state.data._notRelevant=state.data._notRelevant.filter(key=>key!==input.dataset.field)}}const count=issue.fields.filter(field=>present(state.data[field])).length;if(count<2){showControlError('Bitte mindestens zwei Ortsfelder angeben.');return}state.history.push({...issue,resolution:'Ortsangaben bestätigt',resolvedValue:issue.fields.filter(field=>present(state.data[field])).map(field=>`${ENGINE.FIELD_DEFS[field].label}: ${state.data[field]}`).join('; ')})
  }else if(kind==='corrected'){const input=$('issueInput');let value=input?.value?.trim();if(!value){input?.focus();showControlError('Bitte einen Wert auswählen oder eingeben.');return}if(issue.definition?.type==='number'){value=ENGINE.number(value);if(!Number.isFinite(value)){input.focus();showControlError('Bitte einen gültigen Zahlenwert eingeben.');return}}state.data[issue.field]=value;state.data._confidence[issue.field]=1;state.data._notRelevant=(state.data._notRelevant||[]).filter(key=>key!==issue.field);if(state.data._formIdentityDecision==='manual'&&!state.data._manualReviewed.includes(issue.field))state.data._manualReviewed.push(issue.field);state.confirmedFailIds.delete(issue.id);state.history.push({...issue,resolution:'korrigiert / bestätigt',resolvedValue:value})
  }else if(kind==='nrel'){if(issue.notRelevantMode==='value'){state.data[issue.field]='nrel';state.data._confidence[issue.field]=1;state.history.push({...issue,resolution:'fachlich nicht relevant bestätigt',resolvedValue:'nrel'})}else{delete state.data[issue.field];if(!state.data._notRelevant.includes(issue.field))state.data._notRelevant.push(issue.field);state.history.push({...issue,resolution:'optionales Feld nicht relevant',resolvedValue:null})}
  }else{state.confirmedFailIds.add(issue.id);state.history.push({...issue,resolution:issue.status==='fail'?'Abweichung als Mangel bestätigt':'Fehlende Pflichtangabe als Mangel bestätigt',resolvedValue:issue.detected})}refreshPending();state.current=0;renderIssue()}
function resolveFormIdentity(kind){const issue=state.pending[state.current];if(!issue||issue.groupControl!=='formIdentity')return;if(kind==='replace'){reset();return}state.data._formIdentityDecision=kind==='manual'?'manual':'use';if(kind==='manual'){state.data._manualReviewFields=Object.keys(ENGINE.FIELD_DEFS).filter(key=>key!=='protocolType'&&present(state.data[key]));state.data._manualReviewed=[]}state.history.push({...issue,resolution:kind==='manual'?'Formularidentität technisch unsicher · Zuordnung wird manuell geprüft':'Formularidentität technisch unsicher · Formular trotzdem verwendet',resolvedValue:`${Math.round(state.layoutScore*100)} %`});refreshPending();state.current=0;renderIssue()}
function openIssues(){refreshPending();if(!state.pending.length){renderResult();return}setStep(3);renderIssue()}
function resultRow(check){const row=document.createElement('div');row.className=`result-row ${check.status==='fail'?'fail':''}`;row.innerHTML=`<b>${check.status==='fail'?'×':'✓'}</b><div><span>${escapeHtml(check.title)}</span><small>${escapeHtml(check.detail)}</small></div>`;return row}
function renderResult(){refreshPending();if(state.pending.length){setStep(3);renderIssue();return}const result=ENGINE.finalState(state.data,[],state.config,[...state.confirmedFailIds]),plausible=result.plausible;setStep(4);$('verdict').classList.toggle('fail',!plausible);$('verdictIcon').textContent=plausible?'✓':'×';$('verdictTitle').textContent=plausible?'Plausibel':'Nicht plausibel';$('verdictText').textContent=plausible?'Alle erforderlichen Kreuze, Pflichtangaben und Messwerte sind vorhanden, eindeutig und anhand der hinterlegten Regeln plausibel.':'Mindestens ein bestätigter Mangel, eine bestätigte fehlende Pflichtangabe oder ein rechnerisch unplausibler Messwert bleibt bestehen.';const checks=$('resultChecks');checks.replaceChildren();result.checks.filter(item=>item.status==='pass'||item.status==='fail').forEach(item=>checks.append(resultRow(item)));if(!checks.children.length)checks.innerHTML='<p class="muted">Keine numerische Prüfregel war anwendbar.</p>';const log=$('resolutionLog');log.replaceChildren();state.history.forEach(item=>{const failed=state.confirmedFailIds.has(item.id),row=document.createElement('div');row.className=`result-row ${failed?'fail':''}`;row.innerHTML=`<b>${failed?'×':'✓'}</b><div><span>${escapeHtml(item.title)}</span><small>${escapeHtml(item.resolution)}${present(item.resolvedValue)?`: ${escapeHtml(item.resolvedValue==='nrel'?'nicht relevant':displayValue(item.field,item.resolvedValue))}`:''}</small></div>`;log.append(row)});if(!state.history.length)log.innerHTML='<p class="muted">Keine manuelle Klärung erforderlich.</p>'}
function reset(){state.files=[];state.pages=[];state.data={_confidence:{},_confidenceReason:{},_notRelevant:[],_visualPresence:{},_choiceMarks:{},_manualReviewed:[]};state.pending=[];state.history=[];state.confirmedFailIds.clear();state.current=0;state.layoutScore=0;state.formStatus='unknown';state.canMap=false;state.scoreBreakdown={};$('documentInput').value='';$('analysisBar').style.background='';renderFiles();setStep(0)}
function bindDrop(){const drop=$('dropZone');for(const name of ['dragenter','dragover'])drop.addEventListener(name,event=>{event.preventDefault();drop.classList.add('drag')});for(const name of ['dragleave','drop'])drop.addEventListener(name,event=>{event.preventDefault();drop.classList.remove('drag')});drop.addEventListener('drop',event=>addFiles([...event.dataTransfer.files]))}
function summary(){return{version:ENGINE.VERSION,formStatus:state.formStatus,mode:state.mode,layoutScore:state.layoutScore,fieldMappingAvailable:state.canMap,formIdentityDecision:state.data._formIdentityDecision||'',scoreBreakdown:{...state.scoreBreakdown},fieldCount:Object.keys(ENGINE.FIELD_DEFS).filter(key=>present(state.data[key])).length,pending:state.pending.map(item=>({id:item.id,field:item.field,status:item.status,groupControl:item.groupControl,missingRequired:item.missingRequired,allowNotRelevant:item.allowNotRelevant})),data:{...state.data,_fieldEvidence:undefined},history:[...state.history]}}
function init(){if(!ENGINE)throw new Error('VDE-Prüfengine fehlt.');$('documentInput').addEventListener('change',event=>{addFiles([...event.target.files]);event.target.value=''});bindDrop();$('clearFiles').onclick=()=>{state.files=[];renderFiles()};$('startAnalysis').onclick=analyze;$('backUpload').onclick=()=>setStep(0);$('openIssues').onclick=openIssues;$('backReview').onclick=()=>{renderReview();setStep(2)};$('notRelevant').onclick=()=>resolveCurrent('nrel');$('confirmFail').onclick=()=>resolveCurrent('fail');$('applyCorrection').onclick=()=>resolveCurrent('corrected');$('useForm').onclick=()=>resolveFormIdentity('use');$('manualFormReview').onclick=()=>resolveFormIdentity('manual');$('replaceFile').onclick=()=>resolveFormIdentity('replace');$('printResult').onclick=()=>window.print();$('resetAll').onclick=reset;window.SK_VDE_CHECKER=Object.freeze({summary});renderFiles()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();
